In [1]:
import pymysql
import pandas
import mysql.connector  #这个东西是作为一个连接器来链接python和mysql
 
# 打开数据库连接
db = pymysql.connect("localhost","root","xml1997","student" )
 
# 使用 cursor() 方法创建一个游标对象 cursor
cursor = db.cursor()
 
# 使用 execute()  方法执行 SQL 查询 
cursor.execute("SELECT VERSION()")
 
# 使用 fetchone() 方法获取单条数据.
data = cursor.fetchone()
 
print ("Database version : %s " % data)

Database version : 8.0.13

In [2]:
sql = """
show tables
"""
cursor.execute(sql)
print(cursor.fetchall())

sql = """
select * from 微博数据;
"""
cursor.execute(sql)
print(cursor.fetchall())

()

ProgrammingError: (1146, "Table 'student.微博数据' doesn't exist")

In [58]:
import pandas as pd  
from sqlalchemy import create_engine  #这个东西也是建立数据库链接用的
  
##将数据写入mysql的数据库，但需要先通过sqlalchemy.create_engine建立连接,且字符编码设置为utf8，否则有些latin字符不能处理  
yconnect = create_engine('mysql+mysqlconnector://root:xml1997@localhost:3306/train?charset=utf8')  
#pd.io.sql.to_sql(thedataframe,'tablename', yconnect, schema='databasename', if_exists='append')

In [4]:
df = pd.read_excel("D:/studentlist.xlsx")
pd.io.sql.to_sql(df,"studentlist",yconnect,schema="train",if_exists='append')

In [5]:
df

            学号   姓名
0   2016050899   谢洁
1   2016056758  江怡儒
2   2016050902  陈欣馨
3   2016050897  梁璐琪
4   2016050901  纪洁灵
5   2016053073  唐瑛遥
6   2016050904  黄敏哲
7   2016050900  吴泽鑫
8   2016050893  徐铭亮
9   2015052899   甘阳
10  2016053739   来源
11  2016050896  胡洁雯
12  2016050895  吴盈盈
13  2016050080   高露
14  2016056743  林嘉炜
15  2016050906  崔庆海
16  2016056749  刘嘉杨
17  2016050890  梁云波
18  2016050889  黄坤键
19  2015052887  赵彦婷
20  2015052884  马杰薪
21  2016056750  黄子彦

In [49]:
df2 = pd.read_excel("D:/学生.xlsx")

pd.io.sql.to_sql(df2,"学生",yconnect,schema="student",if_exists='append')

In [50]:
df2

,学号,姓名,性别,籍贯,出生日期,入学总分,住校否,爱好特长,简历,密码,登录时间,登录次数
0,2017010001,郑含因,女,广东广州,1999-02-06,712,False,NaN,广州市广雅中学任文体委员,111,2018-10-17 08:31:15,2
1,2017010002,李伯仁,男,湖南长沙,1998-06-16,695,True,书法，国画,湖南长沙第十五中学校田径队成员,222,NaT,0
2,2017010003,陈醉,男,辽宁沈阳,1999-06-12,653,True,足球，篮球,沈阳市第五十六中学任副班长，获三等奖学金。,333,NaT,0
3,2017030001,魏文鼎,男,湖南株洲,1999-04-16,684,True,NaN,NaN,555,NaT,0
4,2017030002,李文如,女,山东青岛,1999-02-23,645,True,NaN,NaN,666,NaT,0
5,2017050001,古琴,女,广东广州,1994-08-15,692,False,NaN,NaN,777,NaT,0
6,2017050002,冯雨,男,北京通县,1995-12-12,701,True,足球，篮球,NaN,888,NaT,0
7,2017050003,丁秋宜,女,广西桂林,1999-01-19,703,False,舞蹈，唱歌,NaN,999,NaT,0
8,2017050004,雷鸣,男,北京丰台,1998-10-20,591,True,足球，篮球,NaN,0,NaT,0

In [59]:
sql="select * from 微博数据"
cursor.execute("show columns from 微博数据;")
clo = cursor.fetchall()
cursor.execute(sql)
stu = cursor.fetchall()
sql = "select * from 微博数据 where zan> 10"
cursor.execute(sql)
zhuan = cursor.fetchall()
zhuan

((2,
  'https://weibo.com/2608809423/GlQrBv7q6?refer_flag=1001030103_',
  '墩布挖白菜',
  'https://weibo.com/2608809423?refer_flag=1001030103_',
  '06月18日00:58',
  '日本进口象印轻巧单手弹盖保温杯黑色480ml179（参加299-150）拍2件231.3含税O网页链接点赞，随机送紅包L墩布挖白菜的秒拍视频06月18日00:58来自微博weibo.c',
  1,
  16,
  0,
  '8'),
 (7,
  'https://weibo.com/2794284831/GlQqDizeo?refer_flag=1001030103_',
  '好心天天分享',
  'https://weibo.com/2794284831?refer_flag=1001030103_',
  '06月18日00:56',
  '【京东】日本进口象印（ZOJIRUSHI）轻巧单手弹盖保温保冷杯壶480ml拍2件满减后【231.3含税】O网页链接06月18日00:56来自微博weibo.c',
  0,
  11,
  34,
  '15'),
 (20,
  'https://weibo.com/5885359931/GlQn8me6B?refer_flag=1001030103_',
  '英伦五花肉',
  'https://weibo.com/5885359931?refer_flag=1001030103_',
  '06月18日00:47',
  '寄英国结账的时候会自动加上关税，寄国内免税哦，所以能便宜很多！而且寄国内万一被税了，BL全包~寄国内地址写中文，汉字！06月18日00:47来自微博weibo.c',
  3,
  24,
  13,
  '16'),
 (32,
  'https://weibo.com/2014149297/GlQlIifUD?refer_flag=1001030103_',
  'NewMakeup',
  'https://weibo.com/2014149297?refer_flag=1001030103_',
  '06月18日00:44',
  '美淘B家，各种精选热卖产品，直接打折，低至45折！比较难得的活动，戳【O网页链接】全网满75刀包邮包税直发到手~BECCA水散粉，了解一下啊。有货有折扣06月18日00:44来自搜狗高速浏',
  3,
  13,
  20,
  '13'))

In [60]:
#sql = "alter table 微博数据 add 指标 varchar(10)"
sql = "select 指标 from 微博数据"
cursor.execute(sql)
cursor.fetchall()
db.commit()

In [16]:
sql = "select * from 微博数据;"
cursor.execute(sql)
weibo = cursor.fetchall()
#print(weibo)
cursor.execute("show columns from 微博数据;")

#print(cursor.fetchall())
'''
for i in weibo:
    print(i[6],i[7],i[8])
    zhibiao = i[6]*0.2 + i[7]* 0.5 + i[8]*0.3
    
    sql = "update  微博数据 set 指标 = %d where weibo_url= '%s';"%(zhibiao,i[1])
    
    cursor.execute(sql)
'''
    
    
    
cursor.execute("select * from 微博数据")
cursor.fetchall()

((0,
  'https://weibo.com/5947429550/GlQrKoNeH?refer_flag=1001030103_',
  '一只_疯了的猪',
  'https://weibo.com/5947429550?refer_flag=1001030103_',
  '06月18日00:59',
  '这点钱对他们来说高吗个个年薪几千万欧元//@一天到晚红烧的小鲶鱼：西班牙穷疯了吧税太高了把这些球员坑惨了这些球员的家人把他们的儿子也坑惨了06月18日00:59来自微博极',
  0,
  0,
  0,
  '0'),
 (1,
  'https://weibo.com/3245393294/GlQrBxls6?refer_flag=1001030103_',
  '咚咚抢咚抢',
  'https://weibo.com/3245393294?refer_flag=1001030103_',
  '06月18日00:58',
  '日本进口象印轻巧单手弹盖保温杯黑色480ml179（参加299-150）拍2件231.3含税O网页链接点赞，随机送紅包L墩布挖白菜的秒拍视频06月18日00:58来自微博weibo.c',
  0,
  3,
  0,
  '1'),
 (2,
  'https://weibo.com/2608809423/GlQrBv7q6?refer_flag=1001030103_',
  '墩布挖白菜',
  'https://weibo.com/2608809423?refer_flag=1001030103_',
  '06月18日00:58',
  '日本进口象印轻巧单手弹盖保温杯黑色480ml179（参加299-150）拍2件231.3含税O网页链接点赞，随机送紅包L墩布挖白菜的秒拍视频06月18日00:58来自微博weibo.c',
  1,
  16,
  0,
  '8'),
 (3,
  'https://weibo.com/1651702074/GlQret6mc?refer_flag=1001030103_',
  '半醉半醒半成熟半俗半雅半疯癫',
  'https://weibo.com/1651702074?refer_flag=1001030103_',
  '06月18日00:57',
  '递延所得税6.广告费15%有效可抵扣递延所得税资产06月18日00:57来自Weibo.in',
  0,
  0,
  0,
  '0'),
 (4,
  'https://weibo.com/2110263203/GlQr3xHbB?refer_flag=1001030103_',
  '有奖活动分享',
  'https://weibo.com/2110263203?refer_flag=1001030103_',
  '06月18日00:57',
  '京东日本进口象印轻巧单手弹盖保温杯黑色480ml179（参加299-150）拍2件231.3含税O网页链接06月18日00:57来自微博weibo.c',
  0,
  4,
  4,
  '3'),
 (5,
  'https://weibo.com/5308402717/GlQqWuLip?refer_flag=1001030103_',
  '白菜活动分享大V',
  'https://weibo.com/5308402717?refer_flag=1001030103_',
  '06月18日00:57',
  '【京东】日本进口象印（ZOJIRUSHI）轻巧单手弹盖保温保冷杯壶480ml拍2件满减后【231.3含税】O网页链接06月18日00:57来自小米Max2大屏大',
  0,
  2,
  0,
  '1'),
 (6,
  'https://weibo.com/2110483645/GlQqH5tQw?refer_flag=1001030103_',
  'VanPeople人在温哥华',
  'https://weibo.com/2110483645?refer_flag=1001030103_',
  '06月18日00:56',
  '匿名帮问：大家温哥华哪里有bally的loafer呀？找了好久没找到…如果找daigou从美国邮寄是不是一定会打税呀？大概多少呢？谢谢大家～O网页链接06月18日00:',
  0,
  0,
  0,
  '0'),
 (7,
  'https://weibo.com/2794284831/GlQqDizeo?refer_flag=1001030103_',
  '好心天天分享',
  'https://weibo.com/2794284831?refer_flag=1001030103_',
  '06月18日00:56',
  '【京东】日本进口象印（ZOJIRUSHI）轻巧单手弹盖保温保冷杯壶480ml拍2件满减后【231.3含税】O网页链接06月18日00:56来自微博weibo.c',
  0,
  11,
  34,
  '15'),
 (8,
  'https://weibo.com/6483831123/GlQqx53lM?refer_flag=1001030103_',
  '种草囤货小技能',
  'https://weibo.com/6483831123?refer_flag=1001030103_',
  '06月18日00:56',
  '2件只要100.09！！！【拍2件100.09】RECIPE水晶喷雾2瓶娜扎同歀，含税的，日常单瓶就要59，现在一瓶才50啊！！果断囤！！！06月18日00:56来自皮皮时',
  8,
  0,
  1,
  '1'),
 (9,
  'https://weibo.com/5951785459/GlQqqgN7I?refer_flag=1001030103_',
  '大盗coffee和sugar的秘密花园517',
  'https://weibo.com/5951785459?refer_flag=1001030103_',
  '06月18日00:55',
  '【日本提高营业税致销量下滑】受政府提高营业税等原因影响，日本汽车产业今年遭遇超出预期的下滑。日本汽车制造商协会（JAMA）主席池文彦（FumihikoIke）称，政府未能为刺激消费采取正确的措施，今年4月份营业税的提升是本土销量萎靡的原因之一，并表示税率上涨后，本土新车销量跌幅达到了两位数。06月18日00:55来自红米Not',
  0,
  0,
  0,
  '0'),
 (10,
  'https://weibo.com/5592164857/GlQqoue3I?refer_flag=1001030103_',
  '凯利国际物流有限公司',
  'https://weibo.com/5592164857?refer_flag=1001030103_',
  '06月18日00:55',
  '广州凯利物流有限公司公司經營中國到柬埔寨金边/西港海運、陸運专线包税到门物流业务，公司在柬埔寨金边有自己独立分公司，時效7-9天全程陸運，10-13天全程海運.O网页链接（#Ins#O网页链接）06月18日00:55来自秒拍视',
  0,
  0,
  0,
  '0'),
 (11,
  'https://weibo.com/5592164857/GlQpYc3SO?refer_flag=1001030103_',
  '凯利国际物流有限公司',
  'https://weibo.com/5592164857?refer_flag=1001030103_',
  '06月18日00:54',
  '广州凯利物流有限公司公司經營中國到柬埔寨金边/西港海運、陸運专线包税O网页链接（#Ins#O网页链接）06月18日00:54来自秒拍视',
  0,
  0,
  0,
  '0'),
 (12,
  'https://weibo.com/5405273164/GlQpsxCBp?refer_flag=1001030103_',
  '买白菜的妹妹',
  'https://weibo.com/5405273164?refer_flag=1001030103_',
  '06月18日00:53',
  '京东日本进口象印轻巧单手弹盖保温杯黑色480ml179（参加299-150）拍2件231.3含税O网页链接06月18日00:53来自微博weibo.c',
  1,
  5,
  7,
  '4'),
 (13,
  'https://weibo.com/6132443324/GlQpnyWh3?refer_flag=1001030103_',
  '小猪6132443324',
  'https://weibo.com/6132443324?refer_flag=1001030103_',
  '06月18日00:53',
  '//@卢麒元:回复@葛星佑:一本鱼麟册，相当于一场革命。//@葛星佑:没有人民立法，不动产登记，直接税的推进困难重重06月18日00:53来自iPhone客',
  0,
  1,
  1,
  '0'),
 (14,
  'https://weibo.com/2039047937/GlQpjnZ6b?refer_flag=1001030103_',
  'Irene_Wayne',
  'https://weibo.com/2039047937?refer_flag=1001030103_',
  '06月18日00:53',
  '简直不知道我投给德国队的钱，到底算是交了信仰税还是智商税06月18日00:53来自Timo送的Andro',
  0,
  3,
  0,
  '1'),
 (15,
  'https://weibo.com/2686783701/GlQoRFvuW?refer_flag=1001030103_',
  'DEALWITHEM',
  'https://weibo.com/2686783701?refer_flag=1001030103_',
  '06月18日00:52',
  'ORBIS奥蜜思和汉净痘美肌隔离乳30g*4件192元包税包邮历史低价O网页链接06月18日00:52来自DEALWITH',
  0,
  0,
  0,
  '0'),
 (16,
  'https://weibo.com/1465226320/GlQoO6q6E?refer_flag=1001030103_',
  '木叶与枇杷',
  'https://weibo.com/1465226320?refer_flag=1001030103_',
  '06月18日00:51',
  '买个机票都能蠢到被收智商税。。。幸亏想到了退税的办法哈哈哈@泡泡龙撒花花06月18日00:51来自HUAWEIP10Pl',
  0,
  0,
  0,
  '0'),
 (17,
  'https://weibo.com/6413043896/GlQoB5BOT?refer_flag=1001030103_',
  '与当下共舞',
  'https://weibo.com/6413043896?refer_flag=1001030103_',
  '06月18日00:51',
  '发表了一篇转载博文《[转载]香港媒体爆出中国房产税征收细则》O[转载]香港媒体爆出中国房产税征收细则06月18日00:51来自新浪',
  0,
  0,
  0,
  '0'),
 (18,
  'https://weibo.com/1362439111/GlQnmglxf?refer_flag=1001030103_',
  'r涩色男鞋dmjawpa',
  'https://weibo.com/1362439111?refer_flag=1001030103_',
  '06月18日00:48',
  '税补上06月18日00:48来自Android客',
  0,
  0,
  0,
  '0'),
 (19,
  'https://weibo.com/1362439111/GlQnhwecs?refer_flag=1001030103_',
  'r涩色男鞋dmjawpa',
  'https://weibo.com/1362439111?refer_flag=1001030103_',
  '06月18日00:48',
  '把税交上再说吧06月18日00:48来自Android客',
  0,
  0,
  0,
  '0'),
 (20,
  'https://weibo.com/5885359931/GlQn8me6B?refer_flag=1001030103_',
  '英伦五花肉',
  'https://weibo.com/5885359931?refer_flag=1001030103_',
  '06月18日00:47',
  '寄英国结账的时候会自动加上关税，寄国内免税哦，所以能便宜很多！而且寄国内万一被税了，BL全包~寄国内地址写中文，汉字！06月18日00:47来自微博weibo.c',
  3,
  24,
  13,
  '16'),
 (21,
  'https://weibo.com/6309798333/GlQmY0STQ?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:47',
  'MCQ麦昆女装€295打八折汇率8.8包税包国际运费06月18日00:47来自iPhon',
  0,
  0,
  0,
  '0'),
 (22,
  'https://weibo.com/6309798333/GlQmL2No3?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:46',
  'MCQ麦昆女装€225打七折汇率8.8包税包国际运费06月18日00:46来自iPhon',
  0,
  0,
  0,
  '0'),
 (23,
  'https://weibo.com/6309798333/GlQmB1Lpa?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:46',
  'MCQ麦昆女装€275打六折汇率8.8包税包国际运费06月18日00:46来自iPhon',
  0,
  0,
  0,
  '0'),
 (24,
  'https://weibo.com/5526016565/GlQmzsTwX?refer_flag=1001030103_',
  '大山里的放牛郎',
  'https://weibo.com/5526016565?refer_flag=1001030103_',
  '06月18日00:46',
  '其实当时分税制我就不看好06月18日00:46来自Andro',
  0,
  0,
  0,
  '0'),
 (25,
  'https://weibo.com/5978944272/GlQmnFMKF?refer_flag=1001030103_',
  'LuY摄食7H',
  'https://weibo.com/5978944272?refer_flag=1001030103_',
  '06月18日00:45',
  '排量不同的车型所要缴纳车船税额度的差别巨大。时间没有等我！征税范围也更加广泛，新车船税法规定乘用车车船税按排气量分为七档征收，相比老标准；最高纳税额度将90倍于最低纳税税额；是你忘了带我走；我左手过目不忘的的萤火……新标准按排量征收的征税结构更加细化。【车船税新政1月1日执行】《中华展开全文c排量不同的车型所要缴纳车船税额度的差别巨大。时间没有等我！征税范围也更加广泛，新车船税法规定乘用车车船税按排气量分为七档征收，相比老标准；最高纳税额度将90倍于最低纳税税额；是你忘了带我走；我左手过目不忘的的萤火……新标准按排量征收的征税结构更加细化。【车船税新政1月1日执行】《中华人民共和国车船税法实施条例》明年1月1日施行。2马鞍山收起全文d06月18日00:45来自iPhone客',
  0,
  0,
  0,
  '0'),
 (26,
  'https://weibo.com/2640803717/GlQmkqASg?refer_flag=1001030103_',
  '雨儿2640803717',
  'https://weibo.com/2640803717?refer_flag=1001030103_',
  '06月18日00:45',
  '我剁手都要买的宝贝（波兰代购专柜款公主之心三件起包邮包税不退不换），快来和我一起瓜分红包波兰代购专柜款公主之心三件起包邮包税不退不换06月18日00:45来自iPhone客',
  0,
  0,
  0,
  '0'),
 (27,
  'https://weibo.com/3249875127/GlQmd1rDY?refer_flag=1001030103_',
  '海淘掌门人',
  'https://weibo.com/3249875127?refer_flag=1001030103_',
  '06月18日00:45',
  '【日亚直邮&亚马逊海外购】【Champion186-0017军工复古风中性款牛仔布渔夫帽】纯棉单宁材质，六片一统拼接，带有透气孔，适合57-59cm头围。204.97元，prime会员免邮含税到手约227元。O网页链接，海外购攻略及白菜折扣汇总：O亚马逊海外购攻略以及年中大促最值得购买的白菜折扣汇总！06月18日00:45来自皮皮时',
  0,
  0,
  0,
  '0'),
 (28,
  'https://weibo.com/1890872061/GlQm5kgcS?refer_flag=1001030103_',
  '沙鱼不紧张',
  'https://weibo.com/1890872061?refer_flag=1001030103_',
  '06月18日00:45',
  '突然想起冯小刚反对房产税提案的事，怪不得怪不得06月18日00:45来自iPhone客',
  0,
  1,
  0,
  '0'),
 (29,
  'https://weibo.com/5525019802/GlQm03pWC?refer_flag=1001030103_',
  '拼命考出CPA',
  'https://weibo.com/5525019802?refer_flag=1001030103_',
  '06月18日00:45',
  '#增值税#错的有点儿惨不忍睹06月18日00:45来自荣耀8美得与众',
  0,
  0,
  1,
  '0'),
 (30,
  'https://weibo.com/6539699789/GlQlVkBzQ?refer_flag=1001030103_',
  '浅安_Rebecca_',
  'https://weibo.com/6539699789?refer_flag=1001030103_',
  '06月18日00:44',
  '【2014年共3.94万辆新能源汽车免征购置税】据国家税务总局统计，2014年9月-12月有29个省市有办理新能源汽车免征车购税手续，共免征车购税新能源汽车3.94万辆，其中乘用车3.38万辆，商用车5615辆。06月18日00:44来自红米Not',
  0,
  0,
  0,
  '0'),
 (31,
  'https://weibo.com/6296870149/GlQlU8sVa?refer_flag=1001030103_',
  '来福乐7258',
  'https://weibo.com/6296870149?refer_flag=1001030103_',
  '06月18日00:44',
  '一查税，原班人马包刮二王，万一都进去鸟，咋办？此时此刻，话，最好不要讲太快、太满的好，毕竟，大部分的人是站在小崔这边滴！06月18日00:44来自荣耀8青春版颜值',
  0,
  0,
  0,
  '0'),
 (32,
  'https://weibo.com/2014149297/GlQlIifUD?refer_flag=1001030103_',
  'NewMakeup',
  'https://weibo.com/2014149297?refer_flag=1001030103_',
  '06月18日00:44',
  '美淘B家，各种精选热卖产品，直接打折，低至45折！比较难得的活动，戳【O网页链接】全网满75刀包邮包税直发到手~BECCA水散粉，了解一下啊。有货有折扣06月18日00:44来自搜狗高速浏',
  3,
  13,
  20,
  '13'),
 (33,
  'https://weibo.com/2731061052/GlQlsD0lW?refer_flag=1001030103_',
  '大白菜网',
  'https://weibo.com/2731061052?refer_flag=1001030103_',
  '06月18日00:43',
  '溶血栓降血压美国进口PipingRock纳豆激酶胶囊100mg*60粒*2瓶天猫优惠券折后￥99包邮包税史低（￥199-100）|PipingRock纳豆激酶胶囊，顾客评价4.9分，现天猫pipingrock海外旗舰店售价￥199，可点此领取￥100天猫优惠券，折后￥99包邮包...O网页链接06月18日00:43来自大白菜网dzL',
  0,
  2,
  0,
  '1'),
 (34,
  'https://weibo.com/6309798333/GlQlruPWP?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:43',
  'MCQ麦昆女装€275打七折汇率8.8包税包国际运费06月18日00:43来自iPhon',
  0,
  0,
  0,
  '0'),
 (35,
  'https://weibo.com/6309798333/GlQlh8eFs?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:43',
  'MCQ麦昆女装€255打六折汇率8.8包税包国际运费06月18日00:43来自iPhon',
  0,
  0,
  2,
  '0'),
 (36,
  'https://weibo.com/6309798333/GlQl2p7U9?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:42',
  'MCQ麦昆女装€180打六折汇率8.8包税包国际运费06月18日00:42来自iPhon',
  0,
  0,
  0,
  '0'),
 (37,
  'https://weibo.com/6309798333/GlQkNgVqL?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:42',
  'MCQ麦昆女装短袖€160打七折，卫衣€260打五折汇率8.8包税包国际运费06月18日00:42来自iPhon',
  0,
  0,
  0,
  '0'),
 (38,
  'https://weibo.com/1764790950/GlQkK4Qo0?refer_flag=1001030103_',
  'flowerchild2018',
  'https://weibo.com/1764790950?refer_flag=1001030103_',
  '06月18日00:41',
  '//@重残_接济://@理性的白痴:2014年底的房地产去库存政策是导致所有人都彻底被房价永远涨的信仰俘虏，从那时起整个国家就疯狂了，现在即使开征房产税但也无济于事，也会进一步恶化居民部门的现金流，现在已经是怎么做都会错的情况了。//@投资舆情:老郭怒了。最近大家火气都起来了，直接怼。06月18日00:41来自iPhone客',
  0,
  0,
  0,
  '0'),
 (39,
  'https://weibo.com/1922126283/GlQkEbgBa?refer_flag=1001030103_',
  '紫绿烤肠',
  'https://weibo.com/1922126283?refer_flag=1001030103_',
  '06月18日00:41',
  '花钱最多多地方是税！好的知道你挣得多了06月18日00:41来自hina床上的iPhone',
  2,
  0,
  0,
  '0'),
 (40,
  'https://weibo.com/6309798333/GlQkiyMR9?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:40',
  'MCQ麦昆女装短袖€155卫衣€265，打五折汇率8.8包税包国际运费06月18日00:40来自iPhon',
  0,
  0,
  0,
  '0'),
 (41,
  'https://weibo.com/3879988722/GlQk2iBsb?refer_flag=1001030103_',
  '墨鱼頭頭华雪业',
  'https://weibo.com/3879988722?refer_flag=1001030103_',
  '06月18日00:40',
  '【大众全新途观重量降低】从大众集团官方获悉：全新一代Tiguan减重50公斤。整备质量的降低有望使得新车的燃油经济性得到提升。此外在动力方面，全新Tiguan在华将推出搭载1.4T和1.8T涡轮增压发动机的车型，当下小排量增压化已经成为一种趋势，，且1.4T车型符合国家购置税减半政策。06月18日00:40来自小米Note3拍人',
  0,
  1,
  0,
  '0'),
 (42,
  'https://weibo.com/6309798333/GlQjJ8Cru?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:39',
  'MCQ麦昆女装€210打六折汇率8.8包税包国际运费06月18日00:39来自iPhon',
  0,
  0,
  0,
  '0'),
 (43,
  'https://weibo.com/6309798333/GlQjbEYP9?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:38',
  'MCQ麦昆女装240打六折汇率8.8包税包国际运费06月18日00:38来自iPhon',
  0,
  0,
  0,
  '0'),
 (44,
  'https://weibo.com/6562378454/GlQj5umLm?refer_flag=1001030103_',
  'Dreams爱你不需要理由',
  'https://weibo.com/6562378454?refer_flag=1001030103_',
  '06月18日00:37',
  '【日本提高营业税致销量下滑】受政府提高营业税等原因影响，日本汽车产业今年遭遇超出预期的下滑。日本汽车制造商协会（JAMA）主席池文彦（FumihikoIke）称，政府未能为刺激消费采取正确的措施，今年4月份营业税的提升是本土销量萎靡的原因之一，并表示税率上涨后，本土新车销量跌幅达到了两位数。06月18日00:37来自微博weibo.c',
  0,
  0,
  0,
  '0'),
 (45,
  'https://weibo.com/3865701849/GlQiugCEQ?refer_flag=1001030103_',
  '邓小梅不要不开心',
  'https://weibo.com/3865701849?refer_flag=1001030103_',
  '06月18日00:36',
  '哦，逃的税给了吗06月18日00:36来自iPhone6sPl',
  0,
  0,
  0,
  '0'),
 (46,
  'https://weibo.com/3249875127/GlQi9gwgT?refer_flag=1001030103_',
  '海淘掌门人',
  'https://weibo.com/3249875127?refer_flag=1001030103_',
  '06月18日00:35',
  '【日亚直邮&亚马逊海外购】【SoriYanagi柳宗理多用途不锈钢盆套装3件套】直径19、23、27厘米的不锈钢盆各一个，一体成型设计，秉承柳宗理厨具朴实简约风格，采用应用于手术刀的18-8的不锈耐酸钢合金。382.48元，prime会员免邮，含税到手约425.78元。O网页链接，攻略：O亚马逊海外购攻略以及年中大促最值得购买的白菜折扣汇总！06月18日00:35来自皮皮时',
  0,
  0,
  0,
  '0'),
 (47,
  'https://weibo.com/6574553698/GlQh9fMHt?refer_flag=1001030103_',
  '用户6574553698',
  'https://weibo.com/6574553698?refer_flag=1001030103_',
  '06月18日00:33',
  '我又被征交了五路一桥一年四百元.车船使用税720元.问题有二:我的车在折旧,价值在打折扣但税不打折.其二,我没用过五路一桥一年365天还要被限行50天..也没见通知我要少交这50天使用税.不许使用还是要交税.06月18日00:33来自Android客',
  0,
  0,
  0,
  '0'),
 (48,
  'https://weibo.com/6309798333/GlQgd1uJa?refer_flag=1001030103_',
  '第九区buy家妞儿',
  'https://weibo.com/6309798333?refer_flag=1001030103_',
  '06月18日00:30',
  'MCQ麦昆女装€465打五折汇率8.8包税包国际运费06月18日00:30来自iPhon',
  0,
  0,
  0,
  '0'),
 (49,
  'https://weibo.com/5893229774/GlQfQiSeZ?refer_flag=1001030103_',
  '吃土大土豆',
  'https://weibo.com/5893229774?refer_flag=1001030103_',
  '06月18日00:29',
  '【包税直邮】见过WayneGoss25%OFF么？吹爆！卖到断货的周年套也25%OFF！周年套：O网页链接面部套：O网页链接眉部套：O网页链接包！税！直邮全球，包括中国。支持吱付宝，满75刀免邮。06月18日00:29来自微博weibo.c',
  4,
  1,
  1,
  '1'))

In [21]:
cursor.execute("select zhuan,zan,ping from 微博数据")
list = cursor.fetchall()

((0, 0, 0),
 (0, 3, 0),
 (1, 16, 0),
 (0, 0, 0),
 (0, 4, 4),
 (0, 2, 0),
 (0, 0, 0),
 (0, 11, 34),
 (8, 0, 1),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (1, 5, 7),
 (0, 1, 1),
 (0, 3, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (3, 24, 13),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 1, 0),
 (0, 0, 1),
 (0, 0, 0),
 (0, 0, 0),
 (3, 13, 20),
 (0, 2, 0),
 (0, 0, 0),
 (0, 0, 2),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (2, 0, 0),
 (0, 0, 0),
 (0, 1, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (0, 0, 0),
 (4, 1, 1))

In [20]:
key = input('转？')
for i in range(len

1

In [61]:
#对学生的操作
sql= """
select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号
"""
cursor.execute(sql)
result =  cursor.fetchall()
student = pd.DataFrame(list(result))
student

      0           1   2   3  4         5
0   郑含因  2017010001  86  必修  3   大学计算机基础
1   李伯仁  2017010002  91  必修  3   大学计算机基础
2    陈醉  2017010003  79  必修  3   大学计算机基础
3   魏文鼎  2017030001  91  必修  3   大学计算机基础
4   李文如  2017030002  86  必修  3   大学计算机基础
5    陈醉  2017010003  76  必修  2      线性代数
6   郑含因  2017010001  82  必修  3    程序设计基础
7   李伯仁  2017010002  80  必修  3    程序设计基础
8    陈醉  2017010003  87  必修  3    程序设计基础
9   魏文鼎  2017030001  85  必修  3    程序设计基础
10  李文如  2017030002  88  必修  3    程序设计基础
11   古琴  2017050001  70  必修  3    程序设计基础
12   古琴  2017050001  90  选修  2   大学生社交礼仪
13  郑含因  2017010001  90  选修  2      日本文化
14   冯雨  2017050002  88  选修  2      日本文化
15  丁秋宜  2017050003  85  选修  2      日本文化
16  丁秋宜  2017050003  75  选修  3      国际保险
17   冯雨  2017050002  70  选修  2      期货贸易
18  丁秋宜  2017050003  85  选修  2      期货贸易
19  李伯仁  2017010002  85  选修  2    企业资产评估
20   陈醉  2017010003  75  选修  2    企业管理实务
21  郑含因  2017010001  75  必修  4     基础会计学
22  李伯仁  2017010002  80  必修  4     基础会计学
23   陈醉  2017010003  55  必修  4     基础会计学
24  李伯仁  2017010002  80  必修  3      税务会计
25   陈醉  2017010003  75  必修  3      税务会计
26  魏文鼎  2017030001  90  必修  3      税务会计
27  魏文鼎  2017030001  85  选修  3     计算机网络
28   冯雨  2017050002  80  选修  3     计算机网络
29  郑含因  2017010001  80  选修  2   房地产法律制度
30  郑含因  2017010001  90  必修  3     普通物理学
31  李伯仁  2017010002  85  必修  3     普通物理学
32  魏文鼎  2017030001  80  必修  2  数据库技术与应用
33  李文如  2017030002  50  必修  2  数据库技术与应用
34  郑含因  2017010001  90  必修  1        体育
35  李伯仁  2017010002  85  必修  1        体育
36   陈醉  2017010003  80  必修  1        体育
37  魏文鼎  2017030001  80  必修  1        体育
38  李文如  2017030002  85  必修  1        体育
39   古琴  2017050001  85  必修  1        体育
40   冯雨  2017050002  90  必修  1        体育
41  丁秋宜  2017050003  75  必修  1        体育
42  魏文鼎  2017030001  78  必修  3     政治经济学
43  李文如  2017030002  80  必修  3     政治经济学
44   古琴  2017050001  80  必修  3     政治经济学
45   冯雨  2017050002  78  必修  3     政治经济学
46  丁秋宜  2017050003  75  必修  3     政治经济学
47  郑含因  2017010001  85  必修  3     经济学原理
48  李伯仁  2017010002  90  必修  3     经济学原理
49   陈醉  2017010003  70  必修  3     经济学原理

In [62]:
sql = """
select 姓名 from 学生
"""
cursor.execute(sql)
res = cursor.fetchall()
student_list = list(res)
student_list = list(set(student_list))
print(res)

(('郑含因',), ('李伯仁',), ('陈醉',), ('魏文鼎',), ('李文如',), ('古琴',), ('冯雨',), ('丁秋宜',), ('雷鸣',))

In [63]:
for i in student_list:
    sql = """
    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '%s';
    """
    print(sql%i)
    cursor.execute(sql%i)
    re = cursor.fetchall()
    df=pd.DataFrame(list(re))
    print(df)

    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '丁秋宜';

     0           1   2   3  4      5
0  丁秋宜  2017050003  85  选修  2   日本文化
1  丁秋宜  2017050003  75  选修  3   国际保险
2  丁秋宜  2017050003  85  选修  2   期货贸易
3  丁秋宜  2017050003  75  必修  1     体育
4  丁秋宜  2017050003  75  必修  3  政治经济学

    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '李伯仁';

     0           1   2   3  4        5
0  李伯仁  2017010002  91  必修  3  大学计算机基础
1  李伯仁  2017010002  80  必修  3   程序设计基础
2  李伯仁  2017010002  85  选修  2   企业资产评估
3  李伯仁  2017010002  80  必修  4    基础会计学
4  李伯仁  2017010002  80  必修  3     税务会计
5  李伯仁  2017010002  85  必修  3    普通物理学
6  李伯仁  2017010002  85  必修  1       体育
7  李伯仁  2017010002  90  必修  3    经济学原理

    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '魏文鼎';

     0           1   2   3  4         5
0  魏文鼎  2017030001  91  必修  3   大学计算机基础
1  魏文鼎  2017030001  85  必修  3    程序设计基础
2  魏文鼎  2017030001  90  必修  3      税务会计
3  魏文鼎  2017030001  85  选修  3     计算机网络
4  魏文鼎  2017030001  80  必修  2  数据库技术与应用
5  魏文鼎  2017030001  80  必修  1        体育
6  魏文鼎  2017030001  78  必修  3     政治经济学

    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '郑含因';

     0           1   2   3  4        5
0  郑含因  2017010001  86  必修  3  大学计算机基础
1  郑含因  2017010001  82  必修  3   程序设计基础
2  郑含因  2017010001  90  选修  2     日本文化
3  郑含因  2017010001  75  必修  4    基础会计学
4  郑含因  2017010001  80  选修  2  房地产法律制度
5  郑含因  2017010001  90  必修  3    普通物理学
6  郑含因  2017010001  90  必修  1       体育
7  郑含因  2017010001  85  必修  3    经济学原理

    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '雷鸣';

Empty DataFrame
Columns: []
Index: []

    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '陈醉';

    0           1   2   3  4        5
0  陈醉  2017010003  79  必修  3  大学计算机基础
1  陈醉  2017010003  76  必修  2     线性代数
2  陈醉  2017010003  87  必修  3   程序设计基础
3  陈醉  2017010003  75  选修  2   企业管理实务
4  陈醉  2017010003  55  必修  4    基础会计学
5  陈醉  2017010003  75  必修  3     税务会计
6  陈醉  2017010003  80  必修  1       体育
7  陈醉  2017010003  70  必修  3    经济学原理

    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '李文如';

     0           1   2   3  4         5
0  李文如  2017030002  86  必修  3   大学计算机基础
1  李文如  2017030002  88  必修  3    程序设计基础
2  李文如  2017030002  50  必修  2  数据库技术与应用
3  李文如  2017030002  85  必修  1        体育
4  李文如  2017030002  80  必修  3     政治经济学

    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '冯雨';

    0           1   2   3  4      5
0  冯雨  2017050002  88  选修  2   日本文化
1  冯雨  2017050002  70  选修  2   期货贸易
2  冯雨  2017050002  80  选修  3  计算机网络
3  冯雨  2017050002  90  必修  1     体育
4  冯雨  2017050002  78  必修  3  政治经济学

    select 学生.姓名,学生.学号,成绩.成绩,课程.课程类别,课程.学分,课程.课程名称 from (课程 inner join 成绩  on 课程.课程编号 = 成绩.课程编号) inner join 学生 on 学生.学号 = 成绩.学号 where 学生.姓名 = '古琴';

    0           1   2   3  4        5
0  古琴  2017050001  70  必修  3   程序设计基础
1  古琴  2017050001  90  选修  2  大学生社交礼仪
2  古琴  2017050001  85  必修  1       体育
3  古琴  2017050001  80  必修  3    政治经济学